model:
  embedding_dim: 64
  dropout: 0.5
training:
  dataset_name: YAGO
  batch_size: 1
  max_epochs: 100
  lr: 0.001
  weight_decay: 1.0e-05
  save_dir: SAVE
  patience: 10
  min_delta: 0.0001
dataset:
  dataset: YAGO
  history_len: 3
  dilate_len: 1
  add_inverse: true
