model:
  embedding_dim: 32
  dropout: 0.5
training:
  dataset_name: YAGO
  batch_size: 1
  max_epochs: 10
  lr: 0.001
  weight_decay: 1.0e-05
  save_dir: SAVE
dataset:
  dataset: YAGO
  history_len: 5
  dilate_len: 1
  add_inverse: true
